stages:
  - build
  - test
  - docs

variables:
  SIF_DEV_NAME: "needle.sif"
  SIF_BASE_NAME: "needle-base.sif"

build_singularity_images:
  stage: build
  tags:
    - shell
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH == "main"'
  script:
    - echo "Building Singularity image..."
    # just use uv to generate the pinned requirements for the container at build time
    - uv export --frozen --no-emit-workspace --no-emit-project > requirements.txt
    - singularity build -F $SIF_BASE_NAME container/singularity_base.def
    - singularity build -F $SIF_DEV_NAME container/singularity_dev.def
  artifacts:
    paths:
      - $SIF_DEV_NAME
      - $SIF_BASE_NAME

test_singularity_images:
  stage: test
  tags:
    - shell
  needs:
    - build_singularity_images
  script:
    - echo "Testing Singularity image..."
    - singularity run $SIF_DEV_NAME pytest ml/tests
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH == "main"'


pages:
  stage: docs
  image: python:3.12-slim
  before_script:
    - apt-get update && apt-get install -y git
    - pip install uv
  script:
    - uv sync --group docs
    - uv run python -m sphinx -T -b html -d docs/_build/doctrees -D language=en docs docs/_build/html
    - mv docs/_build/html public
  artifacts:
    paths:
      - public
  only:
    - branches
