repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first
      - id: check-executables-have-shebangs

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        stages: [pre-commit,pre-push]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        stages: [pre-commit,pre-push]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings, flake8-bugbear, flake8-print]
        stages: [manual]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML, types-requests]
        stages: [manual]

  - repo: local
    hooks:
      - id: no-debug-string
        name: Check for DEBUG string
        language: pygrep
        entry: print("DEBUG*")  # TODO Unsure if this catches everything
        types: [text]
        exclude: ^\.pre-commit-config\.yaml$
