_target_: lightning.Trainer
max_epochs: 20
log_every_n_steps: 10
accelerator: auto
strategy: auto
precision: 32
devices: 1
check_val_every_n_epoch: 1
num_sanity_val_steps: 0
callbacks:
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: "val_loss"
    mode: "min"
    save_top_k: 1
  - _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: "val_loss"
    min_delta: 0.0
    patience: 10
    mode: "min"