_target_: lightning.Trainer
max_epochs: 500
log_every_n_steps: 10
accelerator: auto
strategy: auto
precision: 32
devices: 1
callbacks:
  - _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: "val_loss"
    min_delta: 0.0
    patience: 100
    mode: "min"
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: "val_loss"
    mode: "min"
    save_top_k: 3
    